apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: appsso
    apps.tanzu.vmware.com/workload-type: web
  name: appsso
spec:
  params:
    - name: live-update
      value: "true"
  serviceClaims:
    - name: my-client-claim
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: my-client-claim
  source:
    git:
      ref:
        branch: main
      url: https://github.com/kdnash82/appsso-starter-java.git

